// Domain model derived from the real DB schema (database.types.ts, autogenerated).
// UI labels in Spanish live in this file's label maps, never in the database (ADR 0006).
// The state machine itself is enforced in Postgres (validate_service_order trigger);
// the map below only mirrors it client-side to disable invalid options in the UI.
import type { Database } from '../../core/supabase/database.types';
import type { Customer } from '../customers/customers.models';

export type ServiceOrder = Database['public']['Tables']['service_orders']['Row'];
export type OrderStatusHistoryEntry = Database['public']['Tables']['order_status_history']['Row'];
export type ServiceOrderPhoto = Database['public']['Tables']['service_order_photos']['Row'];
export type Payment = Database['public']['Tables']['payments']['Row'];
export type PaymentMethod = 'cash' | 'transfer' | 'card';

export const PAYMENT_METHOD_LABELS: Record<PaymentMethod, string> = {
  cash: 'Efectivo',
  transfer: 'Transferencia',
  card: 'Tarjeta',
};

export function paymentMethodLabel(method: string): string {
  return PAYMENT_METHOD_LABELS[method as PaymentMethod] ?? method;
}

export type ServiceOrderStatus =
  | 'pending'
  | 'diagnosing'
  | 'repairing'
  | 'waiting_parts'
  | 'ready'
  | 'delivered'
  | 'cancelled';

export type ServiceOrderPriority = 'low' | 'normal' | 'high' | 'urgent';

export const ORDERED_STATUSES: ServiceOrderStatus[] = [
  'pending',
  'diagnosing',
  'repairing',
  'waiting_parts',
  'ready',
  'delivered',
  'cancelled',
];

export const STATUS_LABELS: Record<ServiceOrderStatus, string> = {
  pending: 'Pendiente',
  diagnosing: 'En diagnóstico',
  repairing: 'En reparación',
  waiting_parts: 'Esperando repuesto',
  ready: 'Listo para entrega',
  delivered: 'Entregado',
  cancelled: 'Cancelado',
};

export const PRIORITY_LABELS: Record<ServiceOrderPriority, string> = {
  low: 'Baja',
  normal: 'Normal',
  high: 'Alta',
  urgent: 'Urgente',
};

// Mirrors public.is_valid_service_order_transition() — the DB is the source of truth.
const STATUS_TRANSITIONS: Record<ServiceOrderStatus, ServiceOrderStatus[]> = {
  pending: ['diagnosing', 'cancelled'],
  diagnosing: ['repairing', 'waiting_parts', 'cancelled'],
  repairing: ['waiting_parts', 'ready', 'cancelled'],
  waiting_parts: ['repairing', 'ready', 'cancelled'],
  ready: ['delivered', 'cancelled'],
  delivered: [],
  cancelled: [],
};

export function nextValidStatuses(current: string): ServiceOrderStatus[] {
  return STATUS_TRANSITIONS[current as ServiceOrderStatus] ?? [];
}

export function statusLabel(status: string): string {
  return STATUS_LABELS[status as ServiceOrderStatus] ?? status;
}

export function priorityLabel(priority: string): string {
  return PRIORITY_LABELS[priority as ServiceOrderPriority] ?? priority;
}

export interface ServiceOrderWithCustomer extends ServiceOrder {
  customer: Pick<Customer, 'id' | 'name'> | null;
}

export interface NewServiceOrder {
  customer_id: string;
  equipment_type: string | null;
  brand: string | null;
  model: string | null;
  serial_number: string | null;
  accessories: string | null;
  reported_issue: string | null;
  initial_diagnosis: string | null;
  priority: ServiceOrderPriority;
  assigned_to: string | null;
  estimated_delivery: string | null;
}

export function emptyNewServiceOrder(): NewServiceOrder {
  return {
    customer_id: '',
    equipment_type: null,
    brand: null,
    model: null,
    serial_number: null,
    accessories: null,
    reported_issue: null,
    initial_diagnosis: null,
    priority: 'normal',
    assigned_to: null,
    estimated_delivery: null,
  };
}
