// Domain model derived from the real DB schema (database.types.ts, autogenerated).
// UI labels in Spanish live in this file's label maps, never in the database (ADR 0006).
// The state machine itself is enforced in Postgres (validate_service_order trigger);
// the map below only mirrors it client-side to disable invalid options in the UI.
import type { Database } from '../../core/supabase/database.types';
import type { Customer } from '../customers/customers.models';

export type ServiceOrder = Database['public']['Tables']['service_orders']['Row'];
export type OrderStatusHistoryEntry = Database['public']['Tables']['order_status_history']['Row'];
export type ServiceOrderPhoto = Database['public']['Tables']['service_order_photos']['Row'];
export type Payment = Database['public']['Tables']['payments']['Row'];
export type ServiceOrderDelivery = Database['public']['Tables']['service_order_deliveries']['Row'];
export type PaymentMethod = 'cash' | 'transfer' | 'card';

export const PAYMENT_METHOD_LABELS: Record<PaymentMethod, string> = {
  cash: 'Efectivo',
  transfer: 'Transferencia',
  card: 'Tarjeta',
};

export function paymentMethodLabel(method: string): string {
  return PAYMENT_METHOD_LABELS[method as PaymentMethod] ?? method;
}

export type ServiceOrderStatus =
  | 'pending'
  | 'diagnosing'
  | 'repairing'
  | 'waiting_parts'
  | 'ready'
  | 'delivered'
  | 'cancelled';

export type ServiceOrderPriority = 'low' | 'normal' | 'high' | 'urgent';
export type ServiceOrderWorkType = 'formatting' | 'repair' | 'parts_replacement' | 'warranty' | 'maintenance';
export type ServiceLocation = 'in_store' | 'external_workshop';

export const WORK_TYPE_LABELS: Record<ServiceOrderWorkType, string> = {
  formatting: 'Formateo',
  repair: 'Reparación',
  parts_replacement: 'Cambio de repuesto',
  warranty: 'Garantía',
  maintenance: 'Mantenimiento',
};

export const WORK_TYPE_OPTIONS = Object.keys(WORK_TYPE_LABELS) as ServiceOrderWorkType[];

export function workTypeLabel(type: string): string {
  return WORK_TYPE_LABELS[type as ServiceOrderWorkType] ?? type;
}

export const SERVICE_LOCATION_LABELS: Record<ServiceLocation, string> = {
  in_store: 'En tienda',
  external_workshop: 'Taller externo',
};

export function serviceLocationLabel(location: string): string {
  return SERVICE_LOCATION_LABELS[location as ServiceLocation] ?? location;
}

export const ORDERED_STATUSES: ServiceOrderStatus[] = [
  'pending',
  'diagnosing',
  'repairing',
  'waiting_parts',
  'ready',
  'delivered',
  'cancelled',
];

export const STATUS_LABELS: Record<ServiceOrderStatus, string> = {
  pending: 'Pendiente',
  diagnosing: 'En diagnóstico',
  repairing: 'En reparación',
  waiting_parts: 'Esperando repuesto',
  ready: 'Listo para entrega',
  delivered: 'Entregado',
  cancelled: 'Cancelado',
};

export const PRIORITY_LABELS: Record<ServiceOrderPriority, string> = {
  low: 'Baja',
  normal: 'Normal',
  high: 'Alta',
  urgent: 'Urgente',
};

// Mirrors public.is_valid_service_order_transition() — the DB is the source of truth.
const STATUS_TRANSITIONS: Record<ServiceOrderStatus, ServiceOrderStatus[]> = {
  pending: ['diagnosing', 'repairing', 'cancelled'],
  diagnosing: ['repairing', 'waiting_parts', 'cancelled'],
  repairing: ['waiting_parts', 'ready', 'cancelled'],
  waiting_parts: ['repairing', 'ready', 'cancelled'],
  ready: ['delivered', 'cancelled'],
  delivered: [],
  cancelled: [],
};

export function nextValidStatuses(current: string): ServiceOrderStatus[] {
  return STATUS_TRANSITIONS[current as ServiceOrderStatus] ?? [];
}

export function statusLabel(status: string): string {
  return STATUS_LABELS[status as ServiceOrderStatus] ?? status;
}

export function priorityLabel(priority: string): string {
  return PRIORITY_LABELS[priority as ServiceOrderPriority] ?? priority;
}

export interface ServiceOrderWithCustomer extends ServiceOrder {
  customer: Pick<Customer, 'id' | 'name'> | null;
}

export interface NewServiceOrder {
  customer_id: string;
  equipment_type: string | null;
  brand: string | null;
  model: string | null;
  serial_number: string | null;
  accessories: string | null;
  reported_issue: string | null;
  initial_diagnosis: string | null;
  priority: ServiceOrderPriority;
  assigned_to: string | null;
  estimated_delivery: string | null;
  work_types: ServiceOrderWorkType[];
  backup_requested?: boolean;
}

export interface ServiceOrderDeliveryInput {
  receiver_name: string;
  receiver_document: string | null;
  work_summary: string | null;
  delivery_notes: string | null;
  warranty_days: number;
  warranty_terms: string | null;
}

export function emptyNewServiceOrder(): NewServiceOrder {
  return {
    customer_id: '',
    equipment_type: null,
    brand: null,
    model: null,
    serial_number: null,
    accessories: null,
    reported_issue: null,
    initial_diagnosis: null,
    priority: 'normal',
    assigned_to: null,
    estimated_delivery: null,
    work_types: [],
    backup_requested: false,
  };
}

export function normalizeEquipmentType(raw: string | null): 'laptop' | 'pc' | 'other' {
  if (!raw) return 'other';
  const clean = raw.toLowerCase().trim();
  if (/(laptop|notebook|portatil|portátil|macbook)/i.test(clean)) return 'laptop';
  if (/(pc|desktop|escritorio|computadora|torre|all in one|aio|ordenador)/i.test(clean)) return 'pc';
  return 'other';
}

export function calculateEstimatedMinutes(
  equipmentType: string | null,
  workTypes: ServiceOrderWorkType[] | null | undefined,
  backupRequested: boolean,
  status: ServiceOrderStatus,
  serviceLocation: ServiceLocation = 'in_store',
  timeAdjustment = 0,
): number | null {
  if (status === 'diagnosing') {
    return Math.max(1, 20 + (timeAdjustment || 0));
  }

  if (
    status === 'waiting_parts' ||
    status === 'ready' ||
    status === 'delivered' ||
    status === 'cancelled' ||
    serviceLocation === 'external_workshop'
  ) {
    return 0;
  }

  if (!workTypes || workTypes.length === 0) {
    return null;
  }

  const hasLocalWork = workTypes.some((wt) => wt === 'formatting' || wt === 'maintenance' || wt === 'parts_replacement');

  if (status === 'pending' && workTypes.includes('repair') && !hasLocalWork) {
    return Math.max(1, 20 + (timeAdjustment || 0));
  }

  let minutes = 0;
  let hasLocal = false;
  let unknownLocal = false;
  const normEq = normalizeEquipmentType(equipmentType);

  if (workTypes.includes('formatting')) {
    hasLocal = true;
    minutes += backupRequested ? 120 : 60;
  }

  if (workTypes.includes('maintenance')) {
    hasLocal = true;
    if (normEq === 'laptop') {
      minutes += 60;
    } else if (normEq === 'pc') {
      minutes += 120;
    } else {
      unknownLocal = true;
    }
  }

  if (workTypes.includes('parts_replacement')) {
    hasLocal = true;
    minutes += 60;
  }

  if (status === 'pending' && workTypes.includes('repair')) {
    minutes += 20;
  }

  if (!hasLocal && workTypes.includes('warranty')) {
    return null;
  }

  if (unknownLocal) {
    return null;
  }

  if (!hasLocal && !workTypes.includes('repair')) {
    return null;
  }

  return Math.max(1, minutes + (timeAdjustment || 0));
}
