export interface SpecificationField {
  key: string; label: string; kinds?: string[]; options?: string[]; hint?: string; numeric?: boolean; filter?: boolean;
}
export const SPECIFICATION_FIELDS: SpecificationField[] = [
  { key: 'platform', label: 'Plataforma', kinds: ['processor', 'motherboard'], options: ['AMD', 'Intel'], filter: true },
  { key: 'socket', label: 'Socket', kinds: ['processor', 'motherboard'], filter: true, hint: 'AM4, AM5, LGA1700, LGA1851…' },
  { key: 'family', label: 'Familia', kinds: ['processor'], filter: true },
  { key: 'generation', label: 'Generación / serie', kinds: ['processor'], filter: true },
  { key: 'chipset', label: 'Chipset', kinds: ['motherboard'], filter: true },
  { key: 'memory_type', label: 'Tipo de memoria', kinds: ['processor', 'motherboard', 'memory'], options: ['DDR3', 'DDR4', 'DDR5'], filter: true },
  { key: 'memory_format', label: 'Formato de memoria', kinds: ['motherboard', 'memory'], options: ['DIMM', 'SO-DIMM'], filter: true },
  { key: 'capacity_gb', label: 'Capacidad total del kit (GB)', kinds: ['memory'], numeric: true, filter: true },
  { key: 'modules_per_kit', label: 'Módulos por kit', kinds: ['memory'], numeric: true },
  { key: 'speed', label: 'Velocidad de memoria (MT/s)', kinds: ['memory'], numeric: true, filter: true },
  { key: 'memory_slots', label: 'Ranuras RAM', kinds: ['motherboard'], numeric: true },
  { key: 'max_memory_gb', label: 'RAM máxima (GB)', kinds: ['motherboard'], numeric: true },
  { key: 'board_format', label: 'Formato de placa', kinds: ['motherboard'], options: ['ATX', 'Micro-ATX', 'Mini-ITX', 'E-ATX'], filter: true },
  { key: 'supported_board_formats', label: 'Formatos de placa admitidos', kinds: ['case'], hint: 'Separados por coma: ATX, Micro-ATX, Mini-ITX', filter: true },
  { key: 'includes_psu', label: 'Incluye fuente', kinds: ['case'], options: ['yes', 'no'], filter: true },
  { key: 'psu_format', label: 'Formato de fuente', kinds: ['power_supply'], options: ['ATX', 'SFX', 'SFX-L'] },
  { key: 'supported_psu_formats', label: 'Formatos de fuente admitidos', kinds: ['case'], hint: 'ATX, SFX' },
  { key: 'storage_interface', label: 'Interfaz', kinds: ['storage'], options: ['SATA', 'NVMe'], filter: true },
  { key: 'capacity', label: 'Capacidad', kinds: ['storage'], filter: true },
  { key: 'storage_interfaces', label: 'Interfaces de almacenamiento admitidas', kinds: ['motherboard'], hint: 'SATA, NVMe' },
  { key: 'cooling_type', label: 'Refrigeración', kinds: ['cooling'], options: ['Air', 'Liquid'], filter: true },
  { key: 'supported_sockets', label: 'Sockets del disipador', kinds: ['cooling'], hint: 'AM4, AM5, LGA1700', filter: true },
  { key: 'radiator_mm', label: 'Radiador (mm)', kinds: ['cooling'], numeric: true, filter: true },
  { key: 'supported_radiators_mm', label: 'Radiadores admitidos (mm)', kinds: ['case'], hint: '240, 280, 360' },
  { key: 'height_mm', label: 'Altura del disipador (mm)', kinds: ['cooling'], numeric: true },
  { key: 'max_cooler_height_mm', label: 'Altura máxima de disipador (mm)', kinds: ['case'], numeric: true },
  { key: 'length_mm', label: 'Longitud de GPU (mm)', kinds: ['graphics'], numeric: true },
  { key: 'max_gpu_length_mm', label: 'Longitud máxima de GPU (mm)', kinds: ['case'], numeric: true },
  { key: 'power_watts', label: 'Potencia de fuente (W)', kinds: ['power_supply'], numeric: true, filter: true },
  { key: 'recommended_psu_watts', label: 'Fuente recomendada para GPU (W)', kinds: ['graphics'], numeric: true },
  { key: 'power_connector', label: 'Conectores GPU requeridos', kinds: ['graphics'], hint: 'Ejemplo: 2x8pin; conservar cantidades' },
  { key: 'power_connectors', label: 'Conectores GPU de la fuente', kinds: ['power_supply'], hint: 'Ejemplo: 1x8pin, 2x8pin; solo combinaciones disponibles' },
  { key: 'required_power_connectors', label: 'Conectores placa requeridos', kinds: ['motherboard'], hint: 'Ejemplo: 24pin+8pin; incluir cantidades' },
  { key: 'power_connector_sets', label: 'Conjuntos de conectores para placa', kinds: ['power_supply'], hint: 'Ejemplo: 24pin+8pin, 24pin+2x8pin' },
  { key: 'supported_cpu_codes', label: 'Códigos Deltron de CPU con soporte verificado', kinds: ['motherboard'], hint: 'Separar por comas. No introducir familias genéricas.' },
  { key: 'cpu_support_complete', label: 'Lista de CPU completa', kinds: ['motherboard'], options: ['yes', 'no'] },
  { key: 'bios_confirmed', label: 'BIOS comprobada para los CPU listados', kinds: ['motherboard'], options: ['yes', 'no'] },
  { key: 'bios_version', label: 'Versión BIOS verificada', kinds: ['motherboard'] },
  { key: 'cpu_support_source', label: 'Fuente del soporte CPU / BIOS', kinds: ['motherboard'], hint: 'Enlace de soporte del fabricante y/o referencia de verificación' },
  { key: 'source', label: 'Fuente de las especificaciones', hint: 'Ficha oficial, enlace o referencia verificable' },
  { key: 'notes', label: 'Observaciones técnicas' },
];
export function specificationValueLabel(value: string): string {
  return ({ yes: 'Sí', no: 'No', Air: 'Aire', Liquid: 'Líquida' } as Record<string, string>)[value] ?? value;
}
