// Domain model derived from the real DB schema (database.types.ts, autogenerated).
// UI labels in Spanish live in this file's label maps, never in the database (ADR 0006).
import type { Database } from '../../core/supabase/database.types';

export type Customer = Database['public']['Tables']['customers']['Row'];

export type DocumentType = 'DNI' | 'RUC';

export const DOCUMENT_TYPE_LABELS: Record<DocumentType, string> = {
  DNI: 'DNI',
  RUC: 'RUC',
};

export function documentTypeLabel(type: string | null): string {
  if (type === 'DNI' || type === 'RUC') return DOCUMENT_TYPE_LABELS[type];
  return type ?? '';
}

export interface NewCustomer {
  name: string;
  document_type: DocumentType | null;
  document_number: string | null;
  phone: string | null;
  email: string | null;
  address: string | null;
  notes: string | null;
}

export type CustomerUpdate = Partial<NewCustomer>;
