// Domain model derived from the real DB schema (database.types.ts, autogenerated).
// UI labels in Spanish live in this file's label maps, never in the database (ADR 0006).
// The state machine itself is enforced in Postgres (validate_budget trigger);
// the map below only mirrors it client-side to disable invalid options in the UI.
import type { Database } from '../../core/supabase/database.types';

export type Budget = Database['public']['Tables']['budgets']['Row'];
export type BudgetItem = Database['public']['Tables']['budget_items']['Row'];
export type BudgetStatusHistoryEntry = Database['public']['Tables']['budget_status_history']['Row'];

export type BudgetStatus = 'draft' | 'sent' | 'approved' | 'rejected';

export const BUDGET_STATUS_LABELS: Record<BudgetStatus, string> = {
  draft: 'Borrador',
  sent: 'Enviado',
  approved: 'Aprobado',
  rejected: 'Rechazado',
};

export function budgetStatusLabel(status: string): string {
  return BUDGET_STATUS_LABELS[status as BudgetStatus] ?? status;
}

// Mirrors public.is_valid_budget_transition() — the DB is the source of truth.
const BUDGET_STATUS_TRANSITIONS: Record<BudgetStatus, BudgetStatus[]> = {
  draft: ['sent', 'rejected'],
  sent: ['approved', 'rejected'],
  approved: [],
  rejected: [],
};

export function nextValidBudgetStatuses(current: string): BudgetStatus[] {
  return BUDGET_STATUS_TRANSITIONS[current as BudgetStatus] ?? [];
}

export interface NewBudgetItem {
  description: string;
  quantity: number;
  unit_price: number;
}

export function lineTotal(item: Pick<BudgetItem, 'quantity' | 'unit_price'>): number {
  return Number(item.quantity) * Number(item.unit_price);
}
